### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'respond_to'

### ISSUE THREAD

**Issue by francose** [hult/facebook-chatbot-python#3]
I tried to follow the documentation however i got this error "AttributeError: 'NoneType' object has no attribute 'respond_to'  ". Could please help me to resolve ?

**Comment by hult** [comment]
Hi! If you look at https://github.com/hult/facebook-chatbot-python/blob/170d9c8f1ac3bce01fd9a82c6488c43ab43dac96/server.py#L40, the bot (which has the `respond_to` method) is only created if there is a corpus file called corpus.txt in the project folder (throwing an error if there isn't would have been more helpful). The README has a section about how to generate it. Hope that helps!

**Comment by francose** [comment]
Thank you very much.
